# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_vector', [dirname(__file__)])
        except ImportError:
            import _vector
            return _vector
        if fp is not None:
            try:
                _mod = imp.load_module('_vector', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _vector = swig_import_helper()
    del swig_import_helper
else:
    import _vector
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Vector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Vector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Vector, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _vector.Vector_x_set
    __swig_getmethods__["x"] = _vector.Vector_x_get
    if _newclass:
        x = _swig_property(_vector.Vector_x_get, _vector.Vector_x_set)
    __swig_setmethods__["y"] = _vector.Vector_y_set
    __swig_getmethods__["y"] = _vector.Vector_y_get
    if _newclass:
        y = _swig_property(_vector.Vector_y_get, _vector.Vector_y_set)
    __swig_setmethods__["z"] = _vector.Vector_z_set
    __swig_getmethods__["z"] = _vector.Vector_z_get
    if _newclass:
        z = _swig_property(_vector.Vector_z_get, _vector.Vector_z_set)

    def __init__(self, x=0, y=0, z=0):
        this = _vector.new_Vector(x, y, z)
        try:
            self.this.append(this)
        except:
            self.this = this

    def length(self):
        return _vector.Vector_length(self)

    def normalize(self):
        return _vector.Vector_normalize(self)

    def __str__(self):
        return 'Vector x={} y={} z={}'.format(self.x, self.y, self.z)

    def __add__(self, v2):
        return _vector.Vector___add__(self, v2)

    def __sub__(self, v2):
        return _vector.Vector___sub__(self, v2)

    def __mul__(self, *args):
        return _vector.Vector___mul__(self, *args)

    def __ne__(self, v2):
        return _vector.Vector___ne__(self, v2)

    def __eq__(self, v2):
        return _vector.Vector___eq__(self, v2)
    __swig_destroy__ = _vector.delete_Vector
    __del__ = lambda self: None
Vector_swigregister = _vector.Vector_swigregister
Vector_swigregister(Vector)

# This file is compatible with both classic and new-style classes.


